WIP: Rename aggregatedPhase and aggregatedResult to just Phase and Result
openshift/compliance-operator pull request #405
Opened 2020-08-18 19:26 UTC by jhrozek

Submitting as WIP because my cluster is again down for the day so I'll
look at the results tomorrow.

Jira: OCPBUGSM-8550

2020-08-19 11:42 UTC, jhrozek commented
The cluster failed to install, will re-trigger the tests..
```
 AWS region: us-west-2 (zones: us-west-2a us-west-2b)
level=fatal msg="failed to fetch Master Machines: failed to load asset \"Install Config\": failed to unmarshal install-config.yaml: error converting YAML to JSON: yaml: line 57: did not find expected key"
2020/08/18 19:41:11 Container setup in pod e2e-aws fai
```

2020-08-19 11:42 UTC, jhrozek commented
/retest

2020-08-20 11:51 UTC, jhrozek commented
Looks like the test just timed out:
```
 {"component":"entrypoint","file":"prow/entrypoint/run.go:169","func":"k8s.io/test-infra/prow/entrypoint.Options.ExecuteProcess","level":"error","msg":"Entrypoint received interrupt: terminated","severity":"error","time":"2020-08-19T13:49:22Z"} 
```

2020-08-20 11:52 UTC, jhrozek commented
The new patch just renames the attribute in the README as well.

2020-08-21 05:30 UTC, JAORMX commented
/retest

2020-08-21 08:38 UTC, jhrozek commented
Sigh, CI:
```
error: some steps failed:
  * could not run steps: step e2e-aws failed: template pod "e2e-aws" failed: pod didn't start running within 30 minutes: 
```

2020-08-21 08:38 UTC, jhrozek commented
/retest

2020-08-24 06:55 UTC, JAORMX commented
/test e2e-aws

2020-08-24 08:10 UTC, JAORMX commented
/retest

2020-08-24 10:33 UTC, JAORMX requested changes
Please fix the deploy/operator.yaml file

2020-08-24 13:18 UTC, JAORMX commented
/lgtm

2020-08-24 13:18 UTC, merged