Restart profileparser on failures
openshift/compliance-operator pull request #692
Opened 2021-08-27 14:49 UTC by jhrozek

We used to be too permisive about failures in the profileparser, which
worked fine in the beginning, but doesn't work so well since we started
annotating the objects with the bundle SHA digest during an update and delete
any objects that were not annotated with that digest value - in case
an update operation failed because of a transient error, we would have
skipped annotating that object and ultimately treat it as removed and
delete it. This was happening especially during upgrades where the API
server might be unreachable at some point.

This patch exits the profileparser with a non-zero code on failures as
well as propagates the errors from the client operations to the error
channels so that they are eventually returned to the binary and used for
the error code. This ensures that the profileparser restarts and
hopefully goes through after the restart.

Jira: [OCPBUGSM-32701](https://issues.redhat.com/browse/OCPBUGSM-32701)

2021-08-29 19:11 UTC, jhrozek commented on cmd/manager/profileparser.go
> +	if err != nil {
Done.

2021-08-29 19:11 UTC, jhrozek commented
> uhm... the only way I can think of testing this is by having a container image with invalid content.

Right, let's see if I can craft one. Putting this on hold.
/hold

2021-09-06 14:46 UTC, jhrozek commented
test added, no longer holding

2021-09-06 14:46 UTC, jhrozek commented
/hold cancel

2021-09-07 06:14 UTC, JAORMX requested changes

2021-09-07 06:14 UTC, JAORMX commented on tests/e2e/e2e_test.go
> +					podList := &v1.PodList{}
s/v1/corev1/

2021-09-07 11:50 UTC, jhrozek commented on tests/e2e/e2e_test.go
> +					podList := &v1.PodList{}
oops, IDE optimization fail

2021-09-07 12:02 UTC, JAORMX commented
/retest

2021-09-07 12:15 UTC, JAORMX approved these changes
/lgtm

2021-09-07 13:33 UTC, merged