Add network to api-resources we always fetch
openshift/compliance-operator pull request #785
Opened 2022-01-31 22:41 UTC by Vincent056

The network resource helps us determine the network type of the platform we're running on. 

We add it to the list of resources we always fetch to be able to write a CPE that will verify if the cluster has an OVN/SDN network type

This PR works in conjunction with: https://github.com/ComplianceAsCode/content/pull/8134

2022-02-01 05:32 UTC, Vincent056 commented
/retest

2022-02-01 07:59 UTC, JAORMX approved these changes
/lgtm
/approve

At some point this should be made configurable, so the container doesn't always try to fetch this. e.g. for EKS or potentially Vanilla Kube (hint hint)

2022-02-01 09:39 UTC, Vincent056 commented
> /lgtm /approve
> 
> At some point this should be made configurable, so the container doesn't always try to fetch this. e.g. for EKS or potentially Vanilla Kube (hint hint)

Hi Ozz, good to hear back from you! How’s thing going? That’s a good suggestion, thanks for the hints!

2022-02-03 10:51 UTC, jhrozek approved these changes
/lgtm

2022-02-03 11:09 UTC, jhrozek requested changes
Actually, can you add a changelog blob? I'll merge the other PR so that yours doesn't conflict

2022-02-03 16:19 UTC, merged